### PR TITLE
Fixes #16 and #14

### LINKED ISSUE #16: Upgrade to Android V2 embedding to not rely on deprecated API
V2 is out there for a good while now and the time is ticking: Android Studio presents a warning

> The plugins `bluetooth_enable, share_files_and_screenshot_widgets` use a deprecated version of the Android embedding.
> To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
> If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

### PR DESCRIPTION
**Pull request by MrCsabaToth**
My fork is a fork of @rootasjey

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
I'm not sure if this PR picked up @rootasjey changes as well. I don't see his commits listed.

**Comment by MrCsabaToth** [comment]
@JayTWWM

**Comment by MrCsabaToth** [comment]
?

**Comment by JayTWWM** [comment]
I can't directly merge because of the conflicts..  
I'm out on a month long trek so can't do it from a PC either.
Do you have any suggestions?

**Comment by JayTWWM** [comment]
I'm getting so many conflicts
I'm unable to merge

**Comment by MrCsabaToth** [comment]
@JayTWWM Sorry for your struggles. I saw only conflicts in the pubspec and the lock file due to so many package versions updated. If you are away then please don't be hasted, it can wait until whenever you are back.

**Comment by JayTWWM** [comment]
Done!

**Comment by MrCsabaToth** [comment]
@JayTWWM I'm really sorry to haste you with this. Apparently you were right and my fork of a fork removed a the screenshot feature. I'll have to reintroduce it. So sorry about that.

**Comment by JayTWWM** [comment]
Yes, it removed the screenshot feature, I saw that but thought that you might have some emergency......

**Comment by MrCsabaToth** [comment]
I filed #19 and will produce a PR

**Comment by JayTWWM** [comment]
Thanks

**Comment by MrCsabaToth** [comment]
> Thanks

Don't thank me for screwing it up.
I have a PR now but please revise it carefully and test it as well. I don't think I have time to test before Sunday.

**Comment by JayTWWM** [comment]
I've tested it. Works fine..

**Pull request merged**
